apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: odh-datasources
spec:
  name: odh-prometheus.yaml
  datasources:
    - name: opendatahub
      type: prometheus
      access: direct
      url: http://prometheus-service:9090
      isDefault: true
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
