apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crd.yaml
- service-account.yaml
- role.yaml
- role-binding.yaml
- operator.yaml
namespace: kubeflow
commonLabels:
  kustomize.component: ai-library
images:
- name: quay.io/croberts/ai-library-operator
  newName: quay.io/croberts/ai-library-operator
  digest: sha256:5fbf0d49c30ae782cd6e0f75fbd5de60c01b399e60890530b4fdd68d333be162
generatorOptions:
  disableNameSuffixHash: true
