apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  name: opendatahub
  namespace: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ai-library/cluster
    name: ai-library-cluster
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: ai-library/operator
    # Note:  In order to utilize ai-library, you also need to have Seldon installed    
    name: ai-library-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: superset
    name: superset
  repos:
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/v0.7-branch-openshift
  - name: kf-manifests
    uri: https://github.com/opendatahub-io/manifests/tarball/v0.7-branch-openshift
