apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  name: opendatahub
  namespace: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: ai-library
    name: ai-library
  repos:
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/v0.7-branch-openshift
  - name: kf-manifests
    uri: https://github.com/opendatahub-io/manifests/tarball/v0.7-branch-openshift
  version: v0.7-branch-openshift
