apiVersion: v1
kind: ConfigMap
metadata:
  name: superset
  namespace: opendatahub
data:
  FLASK_APP: superset
  SUPERSET_ADM_PWD: $(SUPERSET_ADMIN_PASSWORD)
  SUPERSET_CONFIG_PATH: /etc/superset/superset_config.py
  superset_config.py: |
    import os

    MAPBOX_API_KEY = os.getenv('MAPBOX_API_KEY', '')
    SQLALCHEMY_DATABASE_URI = '$(SUPERSET_SQLALCHEMY_DB_URI)'
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    SECRET_KEY = os.getenv('SUPERSET_SECRET_KEY','$(SUPERSET_SECRET_KEY)')
    DATA_DIR = '/var/lib/superset'
