apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: opendatahub
  labels:
    app: superset
spec:
  ports:
    - name: 8088-tcp
      port: 8088
      protocol: TCP
      targetPort: 8088
  selector:
    deploymentconfig: superset
  type: ClusterIP
